In [10]:
import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import investpy as inv
import time

# http://www.b3.com.br/pt_br/market-data-e-indices/servicos-de-dados/market-data/consultas/
#boletim-diario/arquivos-para-download/
df_ti = pd.read_csv('TradeInformationConsolidatedFile_20200626_1.csv')
print('Numero de códigos na base de dados= ',len(df_ti))
n_tickers = 0

# Create a list of active tickers
for i in range(len(df_ti)):
    if df_ti.iloc[i,-2]    > 1000:
        if df_ti.iloc[i,3] == 'CASH':
            #print(df_ti.iloc[i,1])
            if n_tickers == 0:
                list_tickers = pd.Series(df_ti.iloc[i,1]+'.SA')
                n_tickers += 1
            else:                
                list_tickers = pd.concat([list_tickers, pd.Series([df_ti.iloc[i,1]+'.SA'])],ignore_index=True)
                n_tickers += 1
    
list_tickers = list_tickers.tolist() 
print('Number of Tickers = ',len(list_tickers))

Numero de códigos na base de dados=  29940
Number of Tickers =  214

In [11]:
df = yf.download(list_tickers,group_by="ticker", start="2017-01-01", end="2030-01-01")
df

[*********************100%***********************]  214 of 214 completed

             LVBI11.SA                                                  \
                  Open        High         Low       Close   Adj Close
Date
2017-01-02         NaN         NaN         NaN         NaN         NaN
2017-01-03         NaN         NaN         NaN         NaN         NaN
2017-01-04         NaN         NaN         NaN         NaN         NaN
2017-01-05         NaN         NaN         NaN         NaN         NaN
2017-01-06         NaN         NaN         NaN         NaN         NaN
...                ...         ...         ...         ...         ...
2020-06-24  121.849998  122.760002  120.760002  121.889999  121.889999
2020-06-25  121.879997  121.900002  121.029999  121.349998  121.349998
2020-06-26  121.349998  125.000000  119.010002  121.750000  121.750000
2020-06-29  121.349998  123.000000  121.209999  122.660004  122.660004
2020-06-30  123.739998  124.449997  122.699997  123.580002  123.580002

                      ITUB4.SA                                   ...  \
             Volume       Open       High        Low      Close  ...
Date                                                             ...
2017-01-02      NaN  22.299999  22.493299  22.206699  22.353300  ...
2017-01-03      NaN  22.559999  23.313299  22.520000  23.299999  ...
2017-01-04      NaN  23.200001  23.486700  23.139999  23.400000  ...
2017-01-05      NaN  23.393299  23.986700  23.206699  23.719999  ...
2017-01-06      NaN  23.693300  23.913300  23.473301  23.799999  ...
...             ...        ...        ...        ...        ...  ...
2020-06-24  14356.0  26.790001  26.920000  25.600000  25.840000  ...
2020-06-25  15874.0  26.030001  26.330000  25.510000  26.150000  ...
2020-06-26  28422.0  25.709999  26.219999  25.540001  25.709999  ...
2020-06-29  10055.0  25.900000  26.520000  25.750000  26.480000  ...
2020-06-30   4424.0  26.219999  26.309999  25.840000  26.100000  ...

             CPLE3.SA                                   JSLG3.SA             \
                  Low      Close  Adj Close    Volume       Open       High
Date
2017-01-02  19.020000  19.100000  14.866782    9700.0   9.110000   9.110000
2017-01-03  19.580000  19.950001  15.528395   41400.0   9.110000   9.400000
2017-01-04  19.860001  19.870001  15.466125    7800.0   9.370000   9.500000
2017-01-05  19.930000  19.940001  15.520609   33200.0   9.500000   9.690000
2017-01-06  19.850000  19.900000  15.489473   28900.0   9.520000   9.700000
...               ...        ...        ...       ...        ...        ...
2020-06-24  59.299999  60.209999  60.209999  321400.0  23.600000  23.969999
2020-06-25  59.480000  61.000000  61.000000  309200.0  22.700001  23.490000
2020-06-26  59.250000  59.919998  59.919998  374100.0  23.340000  23.500000
2020-06-29  58.970001  59.990002  59.990002  383700.0  22.650000  22.740000
2020-06-30  59.130001  59.919998  59.919998  102600.0  22.600000  23.540001


                  Low      Close  Adj Close     Volume
Date
2017-01-02   9.080000   9.080000   8.794849     6700.0
2017-01-03   9.110000   9.350000   9.056370    41800.0
2017-01-04   9.350000   9.350000   9.056370    18200.0
2017-01-05   9.330000   9.520000   9.221031   207400.0
2017-01-06   9.350000   9.380000   9.085427    25700.0
...               ...        ...        ...        ...
2020-06-24  22.540001  22.879999  22.879999  1189200.0
2020-06-25  22.400000  23.410000  23.410000   958700.0
2020-06-26  22.160000  22.500000  22.500000  1061700.0
2020-06-29  21.620001  22.600000  22.600000  1007700.0
2020-06-30  22.180000  23.209999  23.209999   614600.0

[870 rows x 1284 columns]

In [12]:
idx = pd.IndexSlice
columns =df.loc[:,idx[:,'Adj Close']]
df1 = df
for c in columns:
    df1[c[0],'X_Desvio']  = (df[c]-df[c].rolling(20).mean())/df[c].rolling(20).std()
     
df1 = df1.sort_index(axis=1)
df1

             AALR3.SA                                                   \
            Adj Close  Close   High    Low   Open     Volume  X_Desvio
Date
2017-01-02  14.453397  14.60  14.88  14.40  14.62    35900.0       NaN
2017-01-03  14.750383  14.90  15.06  14.57  14.74   357200.0       NaN
2017-01-04  14.750383  14.90  15.04  14.81  14.90   117100.0       NaN
2017-01-05  15.195866  15.35  15.35  14.90  14.90   124300.0       NaN
2017-01-06  15.294861  15.45  15.45  14.94  15.28   151000.0       NaN
...               ...    ...    ...    ...    ...        ...       ...
2020-06-24  10.310000  10.31  10.84  10.21  10.75   905100.0 -0.634768
2020-06-25  10.640000  10.64  10.92  10.04  10.32  1052100.0 -0.444002
2020-06-26  10.200000  10.20  10.66  10.12  10.58   482600.0 -0.952145
2020-06-29  10.180000  10.18  10.40  10.01  10.27   609600.0 -0.971495
2020-06-30  10.320000  10.32  10.40  10.06  10.13   494100.0 -0.805761

             ABCB4.SA                    ...  XPSF11.SA                   \
            Adj Close    Close     High  ...       Open  Volume X_Desvio
Date                                     ...
2017-01-02  10.761507  12.9961  13.2012  ...        NaN     NaN      NaN
2017-01-03  11.222403  13.5527  13.5527  ...        NaN     NaN      NaN
2017-01-04  11.545759  13.9432  13.9823  ...        NaN     NaN      NaN
2017-01-05  11.731740  14.1678  14.2069  ...        NaN     NaN      NaN
2017-01-06  11.844934  14.3045  14.3436  ...        NaN     NaN      NaN
...               ...      ...      ...  ...        ...     ...      ...
2020-06-24  14.400000  14.4000  15.7000  ...        NaN     NaN      NaN
2020-06-25  14.370000  14.3700  14.6200  ...        NaN     NaN      NaN
2020-06-26  14.170000  14.1700  14.5300  ...        NaN     NaN      NaN
2020-06-29  14.100000  14.1000  14.5300  ...        NaN     NaN      NaN
2020-06-30  14.110000  14.1100  14.1600  ...  96.790001  4108.0      NaN

             YDUQ3.SA                                                         \
            Adj Close      Close       High        Low       Open     Volume
Date
2017-01-02  13.660166  15.450000  15.800000  15.410000  15.800000   763000.0
2017-01-03  14.420538  16.309999  16.309999  15.460000  15.620000  1614600.0
2017-01-04  14.349806  16.230000  16.450001  15.850000  16.389999  1562700.0
2017-01-05  14.119926  15.970000  16.389999  15.870000  16.240000  1593300.0
2017-01-06  14.013827  15.850000  16.100000  15.750000  15.980000  1543800.0
...               ...        ...        ...        ...        ...        ...
2020-06-24  35.130001  35.130001  37.020000  34.950001  37.020000  3072300.0
2020-06-25  34.750000  34.750000  35.720001  34.150002  35.240002  2797400.0
2020-06-26  33.090000  33.090000  35.119999  32.799999  34.669998  2391400.0
2020-06-29  34.230000  34.230000  34.400002  32.220001  33.299999  3056800.0
2020-06-30  33.889999  33.889999  34.590000  33.180000  33.669998   868000.0


            X_Desvio
Date
2017-01-02       NaN
2017-01-03       NaN
2017-01-04       NaN
2017-01-05       NaN
2017-01-06       NaN
...              ...
2020-06-24  0.445748
2020-06-25  0.241859
2020-06-26 -0.518756
2020-06-29 -0.196657
2020-06-30 -0.578964

[870 rows x 1498 columns]

In [13]:
df_desvio =df1.loc[:,idx[:,'X_Desvio']]
df_desvio

,AALR3.SA,ABCB4.SA,ABEV3.SA,ALPA4.SA,ALSO3.SA,ALUP11.SA,AMAR3.SA,ANIM3.SA,ARZZ3.SA,AZUL4.SA,...,VRTA12.SA,VULC3.SA,VVAR3.SA,WEGE3.SA,WIZS3.SA,XPIN11.SA,XPLG11.SA,XPML11.SA,XPSF11.SA,YDUQ3.SA
,X_Desvio,X_Desvio,X_Desvio,X_Desvio,X_Desvio,X_Desvio,X_Desvio,X_Desvio,X_Desvio,X_Desvio,...,X_Desvio,X_Desvio,X_Desvio,X_Desvio,X_Desvio,X_Desvio,X_Desvio,X_Desvio,X_Desvio,X_Desvio
Date,,,,,,,,,,,,,,,,,,,,,
2017-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-01-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-01-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-06-24,-0.634768,-0.657804,0.226094,1.168630,-0.213037,-1.640535,-0.427707,0.429686,0.285189,0.180092,...,NaN,0.017204,0.216801,0.963814,0.786995,NaN,NaN,NaN,NaN,0.445748
2020-06-25,-0.444002,-0.774901,1.023325,1.293754,0.004627,-0.928650,-0.498148,0.082571,1.575537,0.129659,...,NaN,0.057041,0.089307,2.282888,0.528571,NaN,NaN,NaN,NaN,0.241859
2020-06-26,-0.952145,-1.180408,0.547083,0.480146,-1.213817,-1.174628,-0.788022,-1.068173,0.574425,-0.323789,...,NaN,-0.069303,-0.311494,2.316002,-0.113539,NaN,NaN,NaN,NaN,-0.518756
2020-06-29,-0.971495,-1.338781,1.065121,0.724424,-0.647716,-0.363519,-0.769333,-0.667703,1.177624,-0.224489,...,NaN,0.416905,0.990452,1.996838,0.240922,NaN,NaN,NaN,NaN,-0.196657
2020-06-30,-0.805761,-1.336602,1.405713,0.874064,-0.711963,-0.796726,-0.180798,-0.250324,1.783419,-0.545997,...,NaN,0.495499,1.226126,1.962047,-0.104660,NaN,NaN,NaN,NaN,-0.578964

In [14]:
ind = df_desvio.columns.levels[0]
ind = ind.tolist()
valores = df_desvio.iloc[-1].tolist()
desvio = pd.Series(valores, index = ind)

desvio

AALR3.SA    -0.805761
ABCB4.SA    -1.336602
ABEV3.SA     1.405713
ALPA4.SA     0.874064
ALSO3.SA    -0.711963
               ...
XPIN11.SA         NaN
XPLG11.SA         NaN
XPML11.SA         NaN
XPSF11.SA         NaN
YDUQ3.SA    -0.578964
Length: 214, dtype: float64

In [19]:
desvio.sort_values(ascending=True).head()

SUZB3.SA    -2.146713
MALL11.SA   -1.937557
RAIL3.SA    -1.677215
MRFG3.SA    -1.483811
CPLE3.SA    -1.454014
dtype: float64

In [20]:
desvio.sort_values(ascending=False).head()

SMTO3.SA    2.528332
GNDI3.SA    2.145546
BIDI4.SA    2.076767
LWSA3.SA    2.069601
RNEW4.SA    2.068148
dtype: float64